"""Mine MarcoFlow's history for lessons that shape MCF. Writes docs/MARCOFLOW_ANALYSIS.md.

Usage: python scripts/analyze_marcoflow.py [--db data/marcoflow.sqlite]

Rules followed (MARCOFLOW_CONTEXT.md):
  * execution questions use PaperTrade with entryTime >= 2026-08-28 only
  * signal-level (SignalObservation) and paper-level (PaperTrade) results are reported separately
  * live rows only; a paper "win" is pnlDollars > 0
"""

from __future__ import annotations

import argparse
import sqlite3
from pathlib import Path

import numpy as np
import pandas as pd

CLEAN = "2026-08-28"
OUT = Path("docs/MARCOFLOW_ANALYSIS.md")
TARGETS = [0.25, 0.5, 0.75, 1.0, 1.5, 2.0]
STOPS = [0.25, 0.5, 0.75, 1.0, 1.5, 2.0]


def md(df: pd.DataFrame, floatfmt: int = 2) -> str:
    df = df.copy()
    for c in df.columns:
        if pd.api.types.is_float_dtype(df[c]):
            df[c] = df[c].map(lambda v: "" if pd.isna(v) else f"{v:.{floatfmt}f}")
    cols = [str(df.index.name or "")] + [str(c) for c in df.columns]
    lines = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for idx, row in df.iterrows():
        lines.append("| " + " | ".join([str(idx)] + [str(v) for v in row.values]) + " |")
    return "\n".join(lines)


def geometry_grid(mfe: np.ndarray, mae: np.ndarray, fallback: np.ndarray, cost: float):
    """Replay target T / stop S on excursions. Both touched -> counted as LOSS (order unknown,
    pessimistic). Neither -> fallback return. Returns win% and expectancy (% per trade, net of cost)."""
    win = pd.DataFrame(index=pd.Index(TARGETS, name="target% \\ stop%"), columns=STOPS, dtype=float)
    exp = win.copy()
    amb = win.copy()
    for T in TARGETS:
        for S in STOPS:
            hit_t, hit_s = mfe >= T, mae >= S
            both = hit_t & hit_s
            r = np.where(hit_t & ~hit_s, T, np.where(hit_s, -S, np.clip(fallback, -S, T)))
            r = r - cost
            win.loc[T, S] = (r > 0).mean() * 100
            exp.loc[T, S] = r.mean()
            amb.loc[T, S] = both.mean() * 100
    return win, exp, amb


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", default="data/marcoflow.sqlite")
    args = ap.parse_args(argv)
    con = sqlite3.connect(args.db)
    out: list[str] = []
    w = out.append

    w("# MarcoFlow deep-dive: lessons for MCF\n")
    w("*Generated by `scripts/analyze_marcoflow.py` from the 2026-10-02 export. Educational only — not financial advice.*\n")
    w("Signal-level = `SignalObservation` (live rows, observed ≥ 8/28, the tracker's own price path). "
      "Paper-level = `PaperTrade` (entries ≥ 8/28, real Alpaca paper fills). They are never mixed.\n")

    obs = pd.read_sql(
        f"""SELECT direction, heat, momentum, rsi, rsiSlope, vwapDistPct, atrPct, volumeRatio, buyPressure,
                   etHour, sessionSlot, marketRegime, vixLevel, assetClass, entryPrice, status, returnPct,
                   maxFavorablePct mfe, maxAdversePct mae, alertedAt, observedAt, resolvedAt
            FROM SignalObservation
            WHERE source='live' AND status IN ('WIN','LOSS','EXPIRED') AND observedAt >= '{CLEAN}'""",
        con,
    )
    obs["resolve_h"] = (pd.to_datetime(obs.resolvedAt, format="ISO8601") -
                        pd.to_datetime(obs.observedAt, format="ISO8601")).dt.total_seconds() / 3600
    trades = pd.read_sql(
        f"""SELECT t.*, o.observedAt, o.entryPrice obsPrice, o.momentum, o.rsi, o.vwapDistPct, o.atrPct obsAtr,
                   o.volumeRatio, o.buyPressure, o.marketRegime, o.vixLevel, o.assetClass, o.status obsStatus
            FROM PaperTrade t LEFT JOIN SignalObservation o ON o.id = t.observationId
            WHERE t.status='CLOSED' AND t.entryTime >= '{CLEAN}'""",
        con,
    )
    for c in ("entryTime", "exitTime", "observedAt"):
        trades[c] = pd.to_datetime(trades[c], format="ISO8601")
    trades["win"] = trades.pnlDollars > 0
    trades["latency_min"] = (trades.entryTime - trades.observedAt).dt.total_seconds() / 60
    trades["hold_min"] = (trades.exitTime - trades.entryTime).dt.total_seconds() / 60
    sgn = trades.direction.map({"LONG": 1, "SHORT": -1})
    trades["entry_slip_pct"] = sgn * (trades.entryPrice / trades.obsPrice - 1) * 100  # + = paid worse

    # ---------------------------------------------------------------- headline
    w("## 1. Headline numbers\n")
    w(f"- Signal level: {len(obs):,} resolved live signals; tracker rule = +0.75% target / −1.5% stop / 4 market-hour horizon "
      f"→ **{(obs.status == 'WIN').mean() * 100:.1f}% WIN**, avg {obs.returnPct.mean():+.3f}% per signal (before any costs). "
      f"Note the tracker *already* used a high-win-rate geometry (stop 2× target) and still stayed under 50%.")
    w(f"- Median signal took **{obs.resolve_h.median():.0f} clock hours** to resolve — the 4-hour horizon counts market hours and "
      "often runs overnight, so signal-level results are **not intraday results**.")
    w(f"- Paper level: {len(trades):,} trades, **{trades.win.mean() * 100:.1f}% win**, "
      f"avg {trades.returnPct.mean():+.3f}%, P&L ${trades.pnlDollars.sum():,.0f}; median hold {trades.hold_min.median():.0f} min.\n")

    # ---------------------------------------------------------------- geometry
    w("## 2. Can exit geometry alone deliver > 50% wins with positive expectancy?\n")
    w("Replays every target/stop pair over each signal's full-horizon max favourable (MFE) / max adverse (MAE) excursion. "
      "If both were touched the order is unknown, so it is counted as a **loss** (pessimistic). "
      "If neither, the horizon return is used (clamped). A 0.10% round-trip cost is charged. Win % / expectancy (% per trade):\n")
    fallback = np.where(obs.status == "EXPIRED", obs.returnPct, 0.0)
    for direction in ("SHORT", "LONG"):
        m = obs.direction == direction
        win, exp, amb = geometry_grid(obs.mfe[m].to_numpy(), obs.mae[m].to_numpy(), fallback[m.to_numpy()], 0.10)
        w(f"### {direction} signals (n={m.sum():,}) — win %\n")
        w(md(win, 1) + "\n")
        w(f"### {direction} signals — expectancy % per trade (net 0.10%)\n")
        w(md(exp, 3) + "\n")
        good = [(T, S) for T in TARGETS for S in STOPS if win.loc[T, S] >= 55 and exp.loc[T, S] > 0]
        w(f"**Pairs with ≥55% win AND positive expectancy: {good if good else 'none'}**\n")
    w("Read: on MarcoFlow's entries, raising the win rate by tightening the target or widening the stop "
      "drives expectancy to ≤ 0 — the signal itself has too little directional edge for geometry to fix. "
      "MCF has to find entries whose *first move* is in our favour, not tune exits on weak entries.\n")

    # ---------------------------------------------------------------- paper geometry
    w("## 3. Same replay on paper trades (real fills)\n")
    w("Uses `peakPct`/`troughPct` recorded while the position was actually held (so excursions are truncated by MarcoFlow's own exits — "
      "an optimistic-for-tight-targets view). Entry slippage is already inside these numbers; 0.05% exit cost added.\n")
    win, exp, _ = geometry_grid(trades.peakPct.to_numpy(), trades.troughPct.to_numpy(), trades.returnPct.to_numpy(), 0.05)
    w("Win %:\n\n" + md(win, 1) + "\n\nExpectancy % per trade:\n\n" + md(exp, 3) + "\n")

    # ---------------------------------------------------------------- latency
    w("## 4. Data timeframe and latency: the signal decays before it is traded\n")
    lat = trades.dropna(subset=["latency_min"]).copy()
    lat["latency"] = pd.cut(lat.latency_min, [-1, 2, 5, 10, 15, 30, 1e9],
                            labels=["≤2m", "2–5m", "5–10m", "10–15m", "15–30m", ">30m"])
    t = lat.groupby("latency", observed=True).agg(
        trades=("id", "size"), win_pct=("win", lambda x: x.mean() * 100), avg_ret=("returnPct", "mean"),
        entry_slip=("entry_slip_pct", "mean"), sig_win=("obsStatus", lambda x: (x == "WIN").mean() * 100))
    w(md(t) + "\n")
    w(f"- Bars came from Yahoo **~15 min delayed**, scanned every 5 min, then entry a median "
      f"**{lat.latency_min.median():.1f} min** after the signal was recorded → effective decision-to-fill lag ≈ 20+ min.")
    w(f"- Average entry is **{lat.entry_slip_pct.mean():+.2f}%** worse than the signal price (positive = paid worse). "
      "That alone is most of the −0.25% per-trade paper loss.")
    w("- MarcoFlow's persistence test priced 15 min of latency at ~14 win-rate points.")
    w("- **MCF implication:** real-time consolidated 1-min bars (or trade stream), decide on bar close, order within seconds; "
      "entries rest at the broker as stop/limit orders at the trigger price so latency can't move the fill.\n")

    # ---------------------------------------------------------------- never worked
    w("## 5. What separates 'never worked' trades from big winners (paper, clean)\n")
    trades["bucket"] = pd.cut(trades.peakPct, [-1, 0.15, 0.5, 1.0, 1e9],
                              labels=["never (<0.15%)", "0.15–0.5%", "0.5–1%", "≥1%"])
    feats = ["latency_min", "entry_slip_pct", "momentum", "rsi", "vwapDistPct", "obsAtr", "volumeRatio",
             "buyPressure", "heat", "entryPrice"]
    f = trades.groupby("bucket", observed=True)[feats].median()
    f.insert(0, "trades", trades.groupby("bucket", observed=True).size())
    w("Medians by peak-move bucket:\n\n" + md(f.T.rename_axis("feature"), 2) + "\n")
    rows = []
    for col in feats:
        s = trades[[col, "bucket"]].dropna()
        if s[col].nunique() < 5:
            continue
        q = pd.qcut(s[col], 5, duplicates="drop")
        never = s.groupby(q, observed=True)["bucket"].apply(lambda b: (b == "never (<0.15%)").mean() * 100)
        rows.append((col, never.iloc[0], never.iloc[-1], never.max() - never.min()))
    nv = pd.DataFrame(rows, columns=["feature", "never% lowest quintile", "never% highest quintile", "spread"]).set_index("feature")
    w("'Never worked' rate in the lowest vs highest quintile of each feature (overall rate "
      f"{(trades.bucket == 'never (<0.15%)').mean() * 100:.1f}%):\n\n" + md(nv.sort_values("spread", ascending=False), 1) + "\n")

    # ---------------------------------------------------------------- time of day
    w("## 6. Time of day\n")
    sig_h = obs.groupby(["etHour", "direction"]).agg(n=("status", "size"),
                                                     win=("status", lambda x: (x == "WIN").mean() * 100),
                                                     avg=("returnPct", "mean")).unstack()
    sig_h.columns = [f"{a}_{b}" for a, b in sig_h.columns]
    w("Signal level by ET hour (horizon may run overnight — see §1):\n\n" + md(sig_h, 2) + "\n")
    trades["et_hour"] = (trades.entryTime - pd.Timedelta(hours=4)).dt.hour
    ph = trades.groupby("et_hour").agg(trades=("id", "size"), win_pct=("win", lambda x: x.mean() * 100),
                                       avg_ret=("returnPct", "mean"), pnl=("pnlDollars", "sum"))
    w("Paper level by ET entry hour (MarcoFlow only entered 9–12 ET; 9 and 12 were later blocked):\n\n" + md(ph) + "\n")

    # ---------------------------------------------------------------- holding time
    w("## 7. Holding time (paper)\n")
    trades["hold"] = pd.cut(trades.hold_min, [-1, 5, 15, 30, 60, 120, 1e9],
                            labels=["≤5m", "5–15m", "15–30m", "30–60m", "1–2h", ">2h"])
    hh = trades.groupby("hold", observed=True).agg(trades=("id", "size"), win_pct=("win", lambda x: x.mean() * 100),
                                                   avg_ret=("returnPct", "mean"), pnl=("pnlDollars", "sum"))
    w(md(hh) + "\n")

    # ---------------------------------------------------------------- alerted + regime + liquidity
    w("## 8. Selection, regime and liquidity (signal level)\n")
    obs["alerted"] = obs.alertedAt.notna()
    sel = obs.groupby(["alerted", "direction"]).agg(n=("status", "size"), win=("status", lambda x: (x == "WIN").mean() * 100),
                                                     avg=("returnPct", "mean"))
    sel.index = [f"{'alerted' if a else 'not alerted'} {d}" for a, d in sel.index]
    w(md(sel.rename_axis("group")) + "\n")
    reg = obs.groupby(["marketRegime", "direction"]).agg(n=("status", "size"), win=("status", lambda x: (x == "WIN").mean() * 100),
                                                         avg=("returnPct", "mean"))
    reg.index = [f"{r} {d}" for r, d in reg.index]
    w(md(reg.rename_axis("regime")) + "\n")
    obs["price_band"] = pd.cut(obs.entryPrice, [0, 5, 10, 20, 50, 100, 1e9], labels=["<$5", "$5–10", "$10–20", "$20–50", "$50–100", ">$100"])
    pb = obs.groupby("price_band", observed=True).agg(n=("status", "size"), win=("status", lambda x: (x == "WIN").mean() * 100),
                                                      avg=("returnPct", "mean"), med_mae=("mae", "median"))
    w("By price band:\n\n" + md(pb) + "\n")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
